/**
 * generated by Xtext 2.13.0
 */
package wodel.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WodelUiModule extends AbstractWodelUiModule {
  public WodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
