/*
 * generated by Xtext 2.25.0
 */
package wodel.dsls.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWodelScopeProvider extends DelegatingScopeProvider {
}
